apiVersion: v1
kind: pod
metadata: 
	name: result-app-pod
	labels:
		name: result-app-pod	
		app: demo-voting-app
spec:
  containers: 
	- name: result-app
	  image: bencer/example-voting-app-result
	  ports: 
		- containerPort: 80