apiVersion: v1
kind: pod
metadata: 
	name: voting-app-pod
	labels:
		name: voting-app-pod	
		app: demo-voting-app
spec:
  containers: 
	- name: vioting-app
	  image: docker/example-voting-app-vote
	  ports: 
		- containerPort: 80